# Generated by Django 5.0.3 on 2024-05-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_project_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
