# Generated by Django 5.0.3 on 2024-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_project_model_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('todo_name', models.CharField(max_length=100)),
                ('todo_description', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
